modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="cupsultimatepackaddons"
version="${file.jarVersion}"
logoFile="logo.png"
displayName="Cup's Ultimate Pack Addons"
authors="Cup"
description='''
Unique Items and More
'''

# DEPENDENCIES =========================================================================================================
[[dependencies.cupsultimatepackaddons]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER
[[dependencies.cupsultimatepackaddons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER
[[dependencies.cupsultimatepackaddons]]
    modId="geckolib3"
    mandatory=true
    versionRange="[1.18-3.0.56,)"
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER

