modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="cupsaddons"
version="${file.jarVersion}"
logoFile="logo.png"
credits="Joel Fulkerth (Firebolt7780): Concept Art"
displayName="Cup's Ultimate Pack Addons"
authors="Cup"
description='''

Addons and other related helper content for Cup's Ultimate Pack and Cup's Ultimate Pack Official Server.

Do not use standalone.
'''

# DEPENDENCIES =========================================================================================================
[[dependencies.cupsaddons]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER
[[dependencies.cupsaddons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER
[[dependencies.cupsaddons]]
    modId="geckolib3"
    mandatory=true
    versionRange="[1.18-3.0.56,)"
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER
[[dependencies.cupsaddons]]
    modId="playeranimator"
    mandatory=true
    versionRange="[0.4.0+1.18,)"
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER

